experimentName: {EXPERIMENT_NAME}
trialCodeDirectory: .
trialCommand: python3 trial.py --data {DATA_PATH} --horizon {HORIZON} --data-size {DATA_SIZE}
searchSpaceFile: search_space.json
tuner:
  name: {OPTIMIZER}
  classArgs:
    optimize_mode: minimize
trialConcurrency: 1
maxTrialNumber: {MAX_TRIALS}
maxExperimentDuration: {MAX_DURATION}
trainingService:
  platform: local
  useActiveGpu: false